public  class Arthmaticcalculations {
    public  void Addition (integer x, integer y) {
        integer z= x+y;
        system.debug('sum = '+ z);

    }
    public void Subtraction (integer x, integer y){
        integer z = x - y;
        system.debug( 'subtraction =' + z);

    }
    public void Multiplication ( integer x, integer y, integer m){
        integer z = x*(y*m);
        system.debug('Multiplication =' + z);
    }
}
