public  class checkDtatypes {
    public  void MethodBoolean() {
       boolean checkBoolean = true;
       system.debug(checkBoolean);
    }
    public  void Methodinteger(){
        integer varfirst = 1;
        integer varsecond = 2;
        system.debug(varfirst + 'and'+varsecond);
       
    }
    public void Stringmethod(){
        string varname = 'Name';
        string var2name = 'Angel';
        system.debug(varname + ':' +var2name);
       
    }
}
