ListDemo.candidatesList();
ListDemo.randomIntegerList();
string index2can = ListDemo.candidatesList2(2);
system.debug('index 2  candidate = '+ index2can);
string index5can = ListDemo.candidatesList2(5);
system.debug('index 5  candidate = '+ index5can);

string indexminus5can = ListDemo.candidatesList2(-5);
system.debug('index -5  candidate = '+ indexminus5can);
string index0can = ListDemo.candidatesList2(0);
system.debug('index 0  candidate = '+ index0can);

ListDemo.AllCats();